
# fetch repository as zip archive
shallow_clone: true

# set clone depth
clone_depth: 16


environment:

    matrix:
        - PYTHON: "C:\\Python27_64"
          PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "64"
          MULTIPROC: "OFF"
          SINGLECORE: "1"
          EXAMPLES: "ON"

        - PYTHON: "C:\\Python27_32"
          PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "32"
          MULTIPROC: "1"
          SINGLECORE: "OFF"
          EXAMPLES: "OFF"

        - PYTHON: "C:\\Python27_64"
          PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "64"
          MULTIPROC: "3"
          SINGLECORE: "OFF"
          EXAMPLES: "OFF"

        - PYTHON: "C:\\Python34_32"
          PYTHON_VERSION: "3.5"
          PYTHON_ARCH: "32"
          MULTIPROC: "2"
          SINGLECORE: "OFF"
          EXAMPLES: "OFF"

        - PYTHON: "C:\\Python34_64"
          PYTHON_VERSION: "3.5"
          PYTHON_ARCH: "64"
          MULTIPROC: "4"
          SINGLECORE: "OFF"
          EXAMPLES: "OFF"

        - PYTHON: "C:\\Python34_64"
          PYTHON_VERSION: "3.5"
          PYTHON_ARCH: "64"
          MULTIPROC: "OFF"
          SINGLECORE: "2"
          EXAMPLES: "ON"

        - PYTHON: "C:\\Python34_32"
          PYTHON_VERSION: "3.5"
          PYTHON_ARCH: "32"
          MULTIPROC: "OFF"
          SINGLECORE: "3"
          EXAMPLES: "OFF"


install:
    # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
    # and all required packages
    - powershell .\\ciscripts\\appveyor\\install.ps1
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    # Install non-conda packages
    - pip install psutil
    - pip install dill
    # Install scoop with explicetly due to pypi problems
    - pip install https://pypi.python.org/packages/source/s/scoop/scoop-0.7.1.release.tar.gz
    # Finally install pypet
    - pip freeze # check installed packages
    - python setup.py install


build: false


test_script:
    - cd ciscripts\\appveyor
    # Full test suite
    - runtests.cmd
